# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'param_setting.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName(_fromUtf8("Settings"))
        Settings.resize(385, 440)
        Settings.setDocumentMode(False)
        self.centralwidget = QtGui.QWidget(Settings)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.widget_11 = QtGui.QWidget(self.centralwidget)
        self.widget_11.setObjectName(_fromUtf8("widget_11"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.widget_11)
        self.horizontalLayout_11.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_9 = QtGui.QLabel(self.widget_11)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_11.addWidget(self.label_9)
        self.lineEdit_5 = QtGui.QLineEdit(self.widget_11)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.horizontalLayout_11.addWidget(self.lineEdit_5)
        self.comboBox = QtGui.QComboBox(self.widget_11)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.horizontalLayout_11.addWidget(self.comboBox)
        self.verticalLayout.addWidget(self.widget_11)
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.widget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtGui.QLineEdit(self.widget)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout.addWidget(self.lineEdit)
        self.pushButton = QtGui.QPushButton(self.widget)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addWidget(self.widget)
        self.widget_5 = QtGui.QWidget(self.centralwidget)
        self.widget_5.setObjectName(_fromUtf8("widget_5"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.widget_5)
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_5 = QtGui.QLabel(self.widget_5)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_5.addWidget(self.label_5)
        self.lineEdit_4 = QtGui.QLineEdit(self.widget_5)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.horizontalLayout_5.addWidget(self.lineEdit_4)
        self.verticalLayout.addWidget(self.widget_5)
        self.widget_2 = QtGui.QWidget(self.centralwidget)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.widget_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_2 = QtGui.QLineEdit(self.widget_2)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.pushButton_2 = QtGui.QPushButton(self.widget_2)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.verticalLayout.addWidget(self.widget_2)
        self.widget_4 = QtGui.QWidget(self.centralwidget)
        self.widget_4.setObjectName(_fromUtf8("widget_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget_4)
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_4 = QtGui.QLabel(self.widget_4)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_4.addWidget(self.label_4)
        self.lineEdit_3 = QtGui.QLineEdit(self.widget_4)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.horizontalLayout_4.addWidget(self.lineEdit_3)
        self.pushButton_3 = QtGui.QPushButton(self.widget_4)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout_4.addWidget(self.pushButton_3)
        self.verticalLayout.addWidget(self.widget_4)
        self.widget_3 = QtGui.QWidget(self.centralwidget)
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(self.widget_3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.spinBox = QtGui.QSpinBox(self.widget_3)
        self.spinBox.setMaximum(1024)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.horizontalLayout_3.addWidget(self.spinBox)
        self.spinBox_2 = QtGui.QSpinBox(self.widget_3)
        self.spinBox_2.setMaximum(1024)
        self.spinBox_2.setObjectName(_fromUtf8("spinBox_2"))
        self.horizontalLayout_3.addWidget(self.spinBox_2)
        self.verticalLayout.addWidget(self.widget_3)
        self.widget_6 = QtGui.QWidget(self.centralwidget)
        self.widget_6.setObjectName(_fromUtf8("widget_6"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.widget_6)
        self.horizontalLayout_6.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_6 = QtGui.QLabel(self.widget_6)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_6.addWidget(self.label_6)
        self.spinBox_3 = QtGui.QSpinBox(self.widget_6)
        self.spinBox_3.setMaximum(1024)
        self.spinBox_3.setObjectName(_fromUtf8("spinBox_3"))
        self.horizontalLayout_6.addWidget(self.spinBox_3)
        self.verticalLayout.addWidget(self.widget_6)
        self.widget_7 = QtGui.QWidget(self.centralwidget)
        self.widget_7.setObjectName(_fromUtf8("widget_7"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.widget_7)
        self.horizontalLayout_7.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_7 = QtGui.QLabel(self.widget_7)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_7.addWidget(self.label_7)
        self.spinBox_4 = QtGui.QSpinBox(self.widget_7)
        self.spinBox_4.setMaximum(2014)
        self.spinBox_4.setObjectName(_fromUtf8("spinBox_4"))
        self.horizontalLayout_7.addWidget(self.spinBox_4)
        self.verticalLayout.addWidget(self.widget_7)
        self.widget_8 = QtGui.QWidget(self.centralwidget)
        self.widget_8.setObjectName(_fromUtf8("widget_8"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.widget_8)
        self.horizontalLayout_8.setContentsMargins(12, 0, -1, 0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_8 = QtGui.QLabel(self.widget_8)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_8.addWidget(self.label_8)
        self.doubleSpinBox = QtGui.QDoubleSpinBox(self.widget_8)
        self.doubleSpinBox.setMaximum(1.0)
        self.doubleSpinBox.setProperty("value", 0.1)
        self.doubleSpinBox.setObjectName(_fromUtf8("doubleSpinBox"))
        self.horizontalLayout_8.addWidget(self.doubleSpinBox)
        self.verticalLayout.addWidget(self.widget_8)
        self.widget_9 = QtGui.QWidget(self.centralwidget)
        self.widget_9.setObjectName(_fromUtf8("widget_9"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.widget_9)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.checkBox_2 = QtGui.QCheckBox(self.widget_9)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.horizontalLayout_9.addWidget(self.checkBox_2)
        self.checkBox = QtGui.QCheckBox(self.widget_9)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.horizontalLayout_9.addWidget(self.checkBox)
        self.verticalLayout.addWidget(self.widget_9)
        self.widget_10 = QtGui.QWidget(self.centralwidget)
        self.widget_10.setObjectName(_fromUtf8("widget_10"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.widget_10)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.pushButton_4 = QtGui.QPushButton(self.widget_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setSizeIncrement(QtCore.QSize(0, 0))
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setStyleSheet(_fromUtf8("background-color: rgb(14, 122, 255);\n"
"color: rgb(255, 255, 255);"))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.horizontalLayout_10.addWidget(self.pushButton_4)
        self.pushButton_5 = QtGui.QPushButton(self.widget_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setStyleSheet(_fromUtf8("background-color: rgba(189, 20, 50, 170);\n"
"color: rgb(255, 255, 255);"))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.horizontalLayout_10.addWidget(self.pushButton_5)
        self.verticalLayout.addWidget(self.widget_10)
        Settings.setCentralWidget(self.centralwidget)

        self.retranslateUi(Settings)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        Settings.setWindowTitle(_translate("Settings", "MainWindow", None))
        self.label_9.setText(_translate("Settings", "Tag", None))
        self.label.setToolTip(_translate("Settings", "<html><head/><body><p><br/></p></body></html>", None))
        self.label.setText(_translate("Settings", "TOBESET", None))
        self.pushButton.setText(_translate("Settings", "Browser", None))
        self.label_5.setToolTip(_translate("Settings", "<html><head/><body><p><br/></p></body></html>", None))
        self.label_5.setText(_translate("Settings", "TOBESET", None))
        self.label_2.setToolTip(_translate("Settings", "<html><head/><body><p><br/></p></body></html>", None))
        self.label_2.setText(_translate("Settings", "TOBESET", None))
        self.pushButton_2.setText(_translate("Settings", "Browser", None))
        self.label_4.setToolTip(_translate("Settings", "<html><head/><body><p><br/></p></body></html>", None))
        self.label_4.setText(_translate("Settings", "TOBESET", None))
        self.pushButton_3.setText(_translate("Settings", "Browser", None))
        self.label_3.setText(_translate("Settings", "TOBESET", None))
        self.label_6.setText(_translate("Settings", "TOBESET", None))
        self.label_7.setText(_translate("Settings", "TOBESET", None))
        self.label_8.setText(_translate("Settings", "TOBESET", None))
        self.checkBox_2.setText(_translate("Settings", "Append to Input H5", None))
        self.checkBox.setText(_translate("Settings", "Force Poisson", None))
        self.pushButton_4.setText(_translate("Settings", "Save", None))
        self.pushButton_5.setText(_translate("Settings", "Cancel", None))

